* looking at the difference between objects and track objects in a ims file.
* what kind of different stats are available between these two objects

In [3]:
import sys

sys.path.append("..")
import os
import time
import numpy as np
import pandas as pd
from typing import List
from utils.data import load_yaml
from imaris.imaris import ImarisDataObject
from parsers.spot_track_object_parser import SpotTrackObjectParserDistributed

In [4]:
#ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/spots/Day2 RFL Gran2 3x3 2h_[ii9_TileScan_003_Merging001_Image_10].ims"
ims_file = "/home/shehan/Documents/projects/nih/projects/ImarisParser/data/errors/KO Sec 2 Roi1 2x2 30min_[ii31_TileScan 3 (Stage 28 of 36) Image 32]_[ims1_2025-08-05T15-16-33.837].ims"
#parser = SpotTrackObjectParserDistributed(ims_file_path=ims_file)
ims = ImarisDataObject(ims_file)
data = ims.data

In [5]:
data.get("Scene8").get("Content").get("Points0").keys()

<KeysViewHDF5 ['Category', 'CreationParameters', 'Factor', 'FactorList', 'LabelColor', 'LabelColorData', 'LabelColorLabelGroupNames', 'LabelColorLabelValues', 'LabelGroupNames', 'LabelSetLabelIDs', 'LabelSetObjectIDs', 'LabelSets', 'LabelValues', 'Spot', 'SpotTimeOffset', 'StatisticsType', 'StatisticsValue', 'StatisticsValueTimeOffset', 'Time', 'TimeBegin']>

In [6]:
pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("Points0").get("StatisticsValue")))

   ID_Time  ID_Object  ID_StatisticsType  Value
0       -1         -1                 13    0.0
1       -1         -1                 12    0.0

In [8]:
data.get("Scene8").get("Content").get("Points0").keys()

<KeysViewHDF5 ['Category', 'CreationParameters', 'Factor', 'FactorList', 'LabelColor', 'LabelColorData', 'LabelColorLabelGroupNames', 'LabelColorLabelValues', 'LabelGroupNames', 'LabelSetLabelIDs', 'LabelSetObjectIDs', 'LabelSets', 'LabelValues', 'Spot', 'SpotTimeOffset', 'StatisticsType', 'StatisticsValue', 'StatisticsValueTimeOffset', 'Time', 'TimeBegin']>

In [3]:
with_tracks = parser.inspect(0)
#no_tracks = parser.inspect(2)

In [6]:
with_tracks["final_df"]

,Acceleration,Acceleration X,Acceleration Y,Acceleration Z,Area,Average Distance To 3 Nearest Neighbours,Average Distance To 5 Nearest Neighbours,Average Distance To 9 Nearest Neighbours,Diameter X,Diameter Y,...,Time Since Track Start,Velocity Angle X,Velocity Angle Y,Velocity Angle Z,Velocity X,Velocity Y,Velocity Z,Volume,Object_ID,Track_ID
15,0.000000,0.000000,0.000000,0.0,323.40918,38.416691,42.779907,49.219017,10.146149,10.146149,...,0.000000,164.578064,74.575386,90.002655,-0.029918,0.008256,0.0,546.892883,15,1000000015
17,0.000000,0.000000,0.000000,0.0,323.40918,20.391607,27.450521,39.842209,10.146149,10.146149,...,0.000000,124.912628,34.909969,90.002655,-0.014694,0.021056,0.0,546.892883,17,1000000017
18,0.000000,0.000000,0.000000,0.0,323.40918,18.563034,27.861975,41.446266,10.146149,10.146149,...,0.000000,131.969849,41.967201,90.002655,-0.020299,0.022571,0.0,546.892883,18,1000000018
19,0.000000,0.000000,0.000000,0.0,323.40918,23.363358,30.175787,40.169548,10.146149,10.146149,...,0.000000,126.505180,36.502518,90.002655,-0.014012,0.018936,0.0,546.892883,19,1000000019
21,0.000000,0.000000,0.000000,0.0,323.40918,34.535027,41.648697,50.248795,10.146149,10.146149,...,0.000000,141.648636,51.645973,90.002655,-0.027949,0.022117,0.0,546.892883,21,1000000021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306083,0.000831,-0.000386,0.000736,0.0,323.40918,55.890827,59.496620,64.215134,10.146149,10.146149,...,100.521004,106.523132,163.484802,90.002655,-0.005764,-0.019434,0.0,546.892883,1306083,1000083995
1306084,0.000574,0.000426,-0.000385,0.0,323.40918,39.863949,46.788063,70.977104,10.146149,10.146149,...,50.252998,84.474953,174.477600,90.002655,0.000234,-0.002415,0.0,546.892883,1306084,1000085988
1306085,0.000404,-0.000358,0.000186,0.0,323.40918,39.980694,46.546227,70.582611,10.146149,10.146149,...,100.297997,75.332512,165.335175,90.002655,0.001950,-0.007450,0.0,546.892883,1306085,1000085988
1306086,0.000364,-0.000149,-0.000332,0.0,323.40918,57.178890,60.456604,70.133453,10.146149,10.146149,...,50.252998,76.466400,13.536255,90.002655,0.001013,0.004206,0.0,546.892883,1306086,1000086111
1306087,0.000033,0.000003,0.000033,0.0,323.40918,57.574696,60.559624,70.310715,10.146149,10.146149,...,100.297997,128.663605,141.344360,90.002655,-0.002652,-0.003315,0.0,546.892883,1306087,1000086111

In [ ]:
final_df_tracks = with_tracks["final_df"]
final_df_no_tracks = no_tracks["stats_df"]

print(
    f"tracks num stats: {final_df_tracks.shape[1]} -- num unique: {len(set(final_df_tracks.columns))}"
)
print(
    f"no_tracks num stats: {final_df_no_tracks.shape[1]} -- num unique: {len(set(final_df_no_tracks.columns))}"
)

In [ ]:
# what stats are missing in no tracks
for stat in list(final_df_tracks.columns):
    if stat not in list(final_df_no_tracks.columns):
        print(stat)